name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd app/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend check
        run: |
          cd app/backend
          python server.py &
          sleep 5
          curl http://127.0.0.1:5000/ping
