name: CI-CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --prefix app/backend && npm install --prefix app/frontend
      - name: Run tests
        run: npm test --prefix app/backend
      - name: Build frontend
        run: npm run build --prefix app/frontend
