apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cxo-friend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cxofriend/backend:6.3.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: env-vars
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cxo-friend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
